dict_orgs = 
{'5CN': array(['Q34'], dtype=object),
 '5D7': array(['Q30'], dtype=object),
 '5D8': array(['Q30'], dtype=object),
 '5JE': array(['Q32'], dtype=object),
 '5M1': array(['Q34'], dtype=object),
 '5N6': array(['Q33'], dtype=object),
 '5P6': array(['Q37'], dtype=object),
 '5PJ': array(['Q34'], dtype=object),
 '5PK': array(['Q34'], dtype=object),
 '5PL': array(['Q34'], dtype=object),
 '5QC': array(['Q38'], dtype=object),
 '5QH': array(['Q39'], dtype=object),
 '5QL': array(['Q39'], dtype=object),
 '5QM': array(['Q39'], dtype=object),
 '5QT': array(['Q38'], dtype=object),
 'R0A': array(['Y54'], dtype=object),
 'R1A': array(['Q34', 'Q53', 'Y55'], dtype=object),
 'R1E': array(['Q34', 'Q60', 'Y55'], dtype=object),
 'R1F': array(['Q38', 'Q70', 'Y57', 'Y59'], dtype=object),
 'R1H': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'R1J': array(['Q64', 'Y57', 'Y58'], dtype=object),
 'R1K': array(['Q71', 'Y56'], dtype=object),
 'RA2': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RA3': array(['Q39', 'Q65', 'Y57', 'Y58'], dtype=object),
 'RA4': array(['Q39', 'Q65', 'Y57', 'Y58'], dtype=object),
 'RA7': array(['Q39', 'Q65', 'Y57', 'Y58'], dtype=object),
 'RA9': array(['Q39', 'Q66', 'Y57', 'Y58'], dtype=object),
 'RAE': array(['Q32', 'Q52', 'Y54'], dtype=object),
 'RAJ': array(['Q35', 'Q57', 'Y55'], dtype=object),
 'RAL': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RAN': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RAP': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RAS': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RAX': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RBA': array(['Q39', 'Q65', 'Y57', 'Y58'], dtype=object),
 'RBB': array(['Q39', 'Q64'], dtype=object),
 'RBD': array(['Q39', 'Q70', 'Y57', 'Y58'], dtype=object),
 'RBF': array(['Q38'], dtype=object),
 'RBK': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RBL': array(['Q31', 'Q44', 'Y54'], dtype=object),
 'RBN': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RBQ': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RBS': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RBT': array(['Q31', 'Q44', 'Y54'], dtype=object),
 'RBV': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RBZ': array(['Q39', 'Q66', 'Y57', 'Y58'], dtype=object),
 'RC1': array(['Q35', 'Q58', 'Y55'], dtype=object),
 'RC3': array(['Q36', 'Q71'], dtype=object),
 'RC9': array(['Q35', 'Q58', 'Y55'], dtype=object),
 'RCB': array(['Q32', 'Q50', 'Y54'], dtype=object),
 'RCC': array(['Q32'], dtype=object),
 'RCD': array(['Q32', 'Q50', 'Y54'], dtype=object),
 'RCF': array(['Q32', 'Q52', 'Y54'], dtype=object),
 'RCU': array(['Q32', 'Q51', 'Y54'], dtype=object),
 'RCX': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RD1': array(['Q39', 'Q64', 'Y57', 'Y58'], dtype=object),
 'RD3': array(['Q39', 'Q70', 'Y57', 'Y58'], dtype=object),
 'RD7': array(['Q38', 'Q69'], dtype=object),
 'RD8': array(['Q38', 'Q58', 'Y55'], dtype=object),
 'RDD': array(['Q35', 'Q57', 'Y55'], dtype=object),
 'RDE': array(['Q35', 'Q57', 'Y55'], dtype=object),
 'RDR': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RDU': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RDY': array(['Q39', 'Q70', 'Y57', 'Y58'], dtype=object),
 'RDZ': array(['Q39', 'Q70', 'Y57', 'Y58'], dtype=object),
 'RE9': array(['Q30', 'Q49', 'Y54'], dtype=object),
 'REF': array(['Q39', 'Q66', 'Y57', 'Y58'], dtype=object),
 'REM': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'REP': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RET': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RF4': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RFF': array(['Q32', 'Q51', 'Y54'], dtype=object),
 'RFR': array(['Q32', 'Q51', 'Y54'], dtype=object),
 'RFS': array(['Q33', 'Q55', 'Y55'], dtype=object),
 'RFW': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RG3': array(['Q36'], dtype=object),
 'RGC': array(['Q36'], dtype=object),
 'RGM': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RGN': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RGP': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RGQ': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RGR': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RGT': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RGZ': array(['Q36'], dtype=object),
 'RH5': array(['Q39', 'Q65', 'Y57', 'Y58'], dtype=object),
 'RH8': array(['Q39', 'Q66', 'Y57', 'Y58'], dtype=object),
 'RHM': array(['Q38', 'Q70', 'Y57', 'Y59'], dtype=object),
 'RHQ': array(['Q32', 'Q51', 'Y54'], dtype=object),
 'RHU': array(['Q38', 'Q70', 'Y57', 'Y59'], dtype=object),
 'RHW': array(['Q38', 'Q69', 'Y57', 'Y59'], dtype=object),
 'RJ1': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RJ2': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RJ6': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RJ7': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RJ8': array(['Q39', 'Q66', 'Y57', 'Y58'], dtype=object),
 'RJC': array(['Q34', 'Q53', 'Y55'], dtype=object),
 'RJD': array(['Q34', 'Q60'], dtype=object),
 'RJE': array(['Q34', 'Q60', 'Y55'], dtype=object),
 'RJF': array(['Q34', 'Q60', 'Y55'], dtype=object),
 'RJL': array(['Q32', 'Q50', 'Y54'], dtype=object),
 'RJN': array(['Q31', 'Q44', 'Y54'], dtype=object),
 'RJR': array(['Q31', 'Q44', 'Y54'], dtype=object),
 'RJZ': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RK5': array(['Q33', 'Q55', 'Y55'], dtype=object),
 'RK9': array(['Q39', 'Q66', 'Y57', 'Y58'], dtype=object),
 'RKB': array(['Q34', 'Q53', 'Y55'], dtype=object),
 'RKE': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RL1': array(['Q34', 'Q60', 'Y55'], dtype=object),
 'RL4': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RLN': array(['Q30', 'Q49', 'Y54'], dtype=object),
 'RLQ': array(['Q34', 'Q53', 'Y55'], dtype=object),
 'RLT': array(['Q34', 'Q53', 'Y55'], dtype=object),
 'RLU': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RM1': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RM2': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RM3': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RM4': array(['Q31'], dtype=object),
 'RMC': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RMP': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RN1': array(['Q38'], dtype=object),
 'RN3': array(['Q39', 'Q64', 'Y57', 'Y58'], dtype=object),
 'RN5': array(['Q38', 'Q70', 'Y57', 'Y59'], dtype=object),
 'RN7': array(['Q37', 'Q67', 'Y57', 'Y59'], dtype=object),
 'RNA': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RNH': array(['Q36'], dtype=object),
 'RNJ': array(['Q36'], dtype=object),
 'RNL': array(['Q31', 'Q49', 'Y54'], dtype=object),
 'RNQ': array(['Q33', 'Q58', 'Y55'], dtype=object),
 'RNS': array(['Q33', 'Q58', 'Y55'], dtype=object),
 'RNZ': array(['Q39', 'Q64', 'Y57', 'Y58'], dtype=object),
 'RP4': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RP5': array(['Q32', 'Q51', 'Y54'], dtype=object),
 'RP6': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RPA': array(['Q37', 'Q67', 'Y57', 'Y59'], dtype=object),
 'RPC': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RPL': array(['Q37'], dtype=object),
 'RPY': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RQ3': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RQ6': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RQ8': array(['Q35', 'Q57', 'Y55'], dtype=object),
 'RQM': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RQQ': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RQW': array(['Q35', 'Q57', 'Y55'], dtype=object),
 'RQX': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RR1': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RR7': array(['Q30', 'Q49', 'Y54'], dtype=object),
 'RR8': array(['Q32', 'Q52', 'Y54'], dtype=object),
 'RRE': array(['Q34', 'Q60', 'Y55'], dtype=object),
 'RRF': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RRJ': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RRK': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RRV': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RT3': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RTD': array(['Q30', 'Q49', 'Y54'], dtype=object),
 'RTE': array(['Q39', 'Q64', 'Y57', 'Y58'], dtype=object),
 'RTF': array(['Q30', 'Q49', 'Y54'], dtype=object),
 'RTG': array(['Q33', 'Q55', 'Y55'], dtype=object),
 'RTH': array(['Q38', 'Q69', 'Y57', 'Y59'], dtype=object),
 'RTK': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RTP': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RTR': array(['Q30', 'Q45', 'Y54'], dtype=object),
 'RTX': array(['Q31', 'Q49', 'Y54'], dtype=object),
 'RV8': array(['Q36', 'Q71'], dtype=object),
 'RVJ': array(['Q39', 'Q65', 'Y57', 'Y58'], dtype=object),
 'RVL': array(['Q36', 'Q71'], dtype=object),
 'RVR': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RVV': array(['Q37', 'Q67', 'Y57', 'Y59'], dtype=object),
 'RVW': array(['Q30', 'Q45', 'Y54'], dtype=object),
 'RVY': array(['Q31', 'Q48', 'Y54'], dtype=object),
 'RW1': array(['Q38', 'Q70', 'Y57', 'Y59'], dtype=object),
 'RW3': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RW6': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RWA': array(['Q32', 'Q50', 'Y54'], dtype=object),
 'RWD': array(['Q33', 'Q59', 'Y55'], dtype=object),
 'RWE': array(['Q33', 'Q59', 'Y55'], dtype=object),
 'RWF': array(['Q37', 'Q67', 'Y57', 'Y59'], dtype=object),
 'RWG': array(['Q35', 'Q58', 'Y55'], dtype=object),
 'RWH': array(['Q35', 'Q58', 'Y55'], dtype=object),
 'RWJ': array(['Q31', 'Q46', 'Y54'], dtype=object),
 'RWP': array(['Q34', 'Q53', 'Y55'], dtype=object),
 'RWW': array(['Q31', 'Q44', 'Y54'], dtype=object),
 'RWY': array(['Q32', 'Q52', 'Y54'], dtype=object),
 'RX1': array(['Q33', 'Q55', 'Y55'], dtype=object),
 'RXC': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RXF': array(['Q32', 'Q52', 'Y54'], dtype=object),
 'RXG': array(['Q32', 'Q52', 'Y54'], dtype=object),
 'RXH': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RXK': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RXL': array(['Q31', 'Q47', 'Y54'], dtype=object),
 'RXN': array(['Q31', 'Q47', 'Y54'], dtype=object),
 'RXP': array(['Q30', 'Q45', 'Y54'], dtype=object),
 'RXQ': array(['Q38', 'Q69', 'Y57', 'Y59'], dtype=object),
 'RXR': array(['Q31', 'Q47', 'Y54'], dtype=object),
 'RXW': array(['Q34', 'Q60', 'Y55'], dtype=object),
 'RY5': array(['Q33', 'Q59', 'Y55'], dtype=object),
 'RYJ': array(['Q36', 'Q71', 'Y56'], dtype=object),
 'RYQ': array(['Q36', 'Q71'], dtype=object),
 'RYR': array(['Q37', 'Q68', 'Y57', 'Y59'], dtype=object),
 'RYV': array(['Q35', 'Q56', 'Y55'], dtype=object),
 'RYW': array(['Q34', 'Q54', 'Y55'], dtype=object),
 'RYX': array(['Q36', 'Q71', 'Y56'], dtype=object)}

dict_names = 
{'5CN': array(['herefordshire pct'], dtype=object),
 '5D7': array(['newcastle pct'], dtype=object),
 '5D8': array(['north tyneside pct'], dtype=object),
 '5JE': array(['barnsley pct'], dtype=object),
 '5M1': array(['south birmingham pct'], dtype=object),
 '5N6': array(['derbyshire county pct'], dtype=object),
 '5P6': array(['west sussex pct'], dtype=object),
 '5PJ': array(['stoke on trent pct'], dtype=object),
 '5PK': array(['south staffordshire pct'], dtype=object),
 '5PL': array(['worcestershire pct'], dtype=object),
 '5QC': array(['hampshire pct'], dtype=object),
 '5QH': array(['gloucestershire pct'], dtype=object),
 '5QL': array(['somerset pct'], dtype=object),
 '5QM': array(['dorset pct'], dtype=object),
 '5QT': array(['isle of wight nhs pct'], dtype=object),
 'R0A': array(['manchester university nhs foundation trust'], dtype=object),
 'R1A': array(['worcestershire health and care nhs trust'], dtype=object),
 'R1E': array(['staffordshire and stoke on trent partnership nhs trust'],
       dtype=object),
 'R1F': array(['isle of wight nhs trust'], dtype=object),
 'R1H': array(['barts health nhs trust'], dtype=object),
 'R1J': array(['gloucestershire care services nhs trust'], dtype=object),
 'R1K': array(['london north west healthcare nhs trust',
        'london north west university healthcare nhs trust'], dtype=object),
 'RA2': array(['royal surrey county hospital nhs trust',
        'royal surrey county nhs foundation trust',
        'royal surrey county hospital nhs foundation trust'], dtype=object),
 'RA3': array(['weston area health nhs trust'], dtype=object),
 'RA4': array(['yeovil district hospital nhs foundation trust'], dtype=object),
 'RA7': array(['university hospitals bristol nhs foundation trust'], dtype=object),
 'RA9': array(['south devon healthcare nhs foundation trust',
        'torbay and south devon nhs foundation trust'], dtype=object),
 'RAE': array(['bradford teaching hospitals nhs foundation trust'], dtype=object),
 'RAJ': array(['southend university hospital nhs foundation trust'], dtype=object),
 'RAL': array(['royal free hampstead nhs trust',
        'royal free london nhs foundation trust'], dtype=object),
 'RAN': array(['royal national orthopaedic hospital nhs trust'], dtype=object),
 'RAP': array(['north middlesex university hospital nhs trust'], dtype=object),
 'RAS': array(['the hillingdon hospital nhs trust',
        'the hillingdon hospitals nhs foundation trust'], dtype=object),
 'RAX': array(['kingston hospital nhs trust',
        'kingston hospital nhs foundation trust'], dtype=object),
 'RBA': array(['taunton and somerset nhs foundation trust'], dtype=object),
 'RBB': array(['royal national hospital for rheumatic diseases nhs foundation trust'],
       dtype=object),
 'RBD': array(['dorset county hospital nhs foundation trust'], dtype=object),
 'RBF': array(['nuffield orthopaedic centre nhs trust'], dtype=object),
 'RBK': array(['walsall hospitals nhs trust', 'walsall healthcare nhs trust'],
       dtype=object),
 'RBL': array(['wirral university teaching hospital nhs foundation trust'],
       dtype=object),
 'RBN': array(['st helens and knowsley hospitals nhs trust',
        'st helens and knowsley hospital services nhs trust',
        'st helens and knowsley teaching hospitals nhs trust'],
       dtype=object),
 'RBQ': array(['liverpool heart and chest hospital nhs trust',
        'liverpool heart and chest nhs foundation trust',
        'liverpool heart and chest hospital nhs foundation trust'],
       dtype=object),
 'RBS': array(["alder hey children's nhs foundation trust"], dtype=object),
 'RBT': array(['mid cheshire hospitals nhs foundation trust'], dtype=object),
 'RBV': array(['the christie nhs foundation trust'], dtype=object),
 'RBZ': array(['northern devon healthcare nhs trust'], dtype=object),
 'RC1': array(['bedford hospital nhs trust'], dtype=object),
 'RC3': array(['ealing hospital nhs trust'], dtype=object),
 'RC9': array(['luton and dunstable hospital nhs foundation trust',
        'luton and dunstable university hospital nhs foundation trust'],
       dtype=object),
 'RCB': array(['york hospitals nhs foundation trust',
        'york teaching hospital nhs foundation trust'], dtype=object),
 'RCC': array(['scarborough and north east yorkshire health care nhs trust'],
       dtype=object),
 'RCD': array(['harrogate and district nhs foundation trust'], dtype=object),
 'RCF': array(['airedale nhs trust', 'airedale nhs foundation trust'],
       dtype=object),
 'RCU': array(['sheffield childrens nhs foundation trust',
        "sheffield children's nhs foundation trust"], dtype=object),
 'RCX': array(["the queen elizabeth hospital king's lynn nhs trust",
        "the queen elizabeth hospital, king's lynn. nhs foundation trust",
        "the queen elizabeth hospital, king's lynn, nhs foundation trust"],
       dtype=object),
 'RD1': array(['royal united hospital bath nhs trust',
        'royal united hospital bath nhs foundation trust',
        'royal united hospitals bath nhs foundation trust'], dtype=object),
 'RD3': array(['poole hospital nhs foundation trust'], dtype=object),
 'RD7': array(['heatherwood and wexham park hospitals nhs foundation trust'],
       dtype=object),
 'RD8': array(['milton keynes hospital nhs foundation trust',
        'milton keynes university hospital nhs foundation trust'],
       dtype=object),
 'RDD': array(['basildon and thurrock university hospitals nhs foundation trust'],
       dtype=object),
 'RDE': array(['colchester hospital university nhs foundation trust',
        'east suffolk and north essex nhs foundation trust'], dtype=object),
 'RDR': array(['sussex community nhs trust',
        'sussex community nhs foundation trust'], dtype=object),
 'RDU': array(['frimley park hospital nhs foundation trust',
        'frimley health nhs foundation trust'], dtype=object),
 'RDY': array(['dorset healthcare university nhs foundation trust'], dtype=object),
 'RDZ': array(['the royal bournemouth and christchurch hospitals nhs foundation trust'],
       dtype=object),
 'RE9': array(['south tyneside nhs foundation trust'], dtype=object),
 'REF': array(['royal cornwall hospitals nhs trust'], dtype=object),
 'REM': array(['aintree university hospitals nhs foundation trust',
        'aintree university hospital nhs foundation trust'], dtype=object),
 'REP': array(["liverpool women's nhs foundation trust"], dtype=object),
 'RET': array(['the walton centre nhs foundation trust'], dtype=object),
 'RF4': array(['barking, havering and redbridge hospitals nhs trust',
        'barking, havering and redbridge university hospitals nhs trust'],
       dtype=object),
 'RFF': array(['barnsley hospital nhs foundation trust'], dtype=object),
 'RFR': array(['the rotherham nhs foundation trust'], dtype=object),
 'RFS': array(['chesterfield royal hospital nhs foundation trust'], dtype=object),
 'RFW': array(['west middlesex university hospital nhs trust'], dtype=object),
 'RG3': array(['bromley hospitals nhs trust'], dtype=object),
 'RGC': array(['whipps cross university hospital nhs trust'], dtype=object),
 'RGM': array(['papworth hospital nhs foundation trust',
        'royal papworth hospital nhs foundation trust'], dtype=object),
 'RGN': array(['peterborough and stamford hospitals nhs foundation trust',
        'north west anglia nhs foundation trust'], dtype=object),
 'RGP': array(['james paget university hospitals nhs foundation trust'],
       dtype=object),
 'RGQ': array(['ipswich hospital nhs trust'], dtype=object),
 'RGR': array(['west suffolk hospitals nhs trust',
        'west suffolk nhs foundation trust'], dtype=object),
 'RGT': array(['cambridge university hospitals nhs foundation trust'],
       dtype=object),
 'RGZ': array(["queen mary's sidcup nhs trust"], dtype=object),
 'RH5': array(['somerset partnership nhs foundation trust'], dtype=object),
 'RH8': array(['royal devon and exeter nhs foundation trust'], dtype=object),
 'RHM': array(['southampton university hospitals nhs trust',
        'university hospital southampton nhs foundation trust'],
       dtype=object),
 'RHQ': array(['sheffield teaching hospitals nhs foundation trust'], dtype=object),
 'RHU': array(['portsmouth hospitals nhs trust'], dtype=object),
 'RHW': array(['royal berkshire hospital nhs foundation trust',
        'royal berkshire nhs foundation trust'], dtype=object),
 'RJ1': array(["guy's and st thomas' nhs foundation trust"], dtype=object),
 'RJ2': array(['the lewisham hospital nhs trust', 'lewisham healthcare nhs trust',
        'lewisham and greenwich nhs trust'], dtype=object),
 'RJ6': array(['mayday healthcare nhs trust', 'croydon health services nhs trust'],
       dtype=object),
 'RJ7': array(["st george's healthcare nhs trust",
        "st george's university hospitals nhs foundation trust"],
       dtype=object),
 'RJ8': array(['cornwall partnership nhs trust',
        'cornwall partnership nhs foundation trust'], dtype=object),
 'RJC': array(['south warwickshire general hospitals nhs trust',
        'south warwickshire nhs foundation trust'], dtype=object),
 'RJD': array(['mid staffordshire nhs foundation trust'], dtype=object),
 'RJE': array(['university hospital of north staffordshire nhs trust',
        'university hospitals of north midlands nhs trust'], dtype=object),
 'RJF': array(['burton hospitals nhs foundation trust'], dtype=object),
 'RJL': array(['northern lincolnshire and goole hospitals nhs foundation trust',
        'northern lincolnshire and goole nhs foundation trust'],
       dtype=object),
 'RJN': array(['east cheshire nhs trust'], dtype=object),
 'RJR': array(['countess of chester hospital nhs foundation trust'], dtype=object),
 'RJZ': array(["king's college hospital nhs foundation trust"], dtype=object),
 'RK5': array(['sherwood forest hospitals nhs foundation trust'], dtype=object),
 'RK9': array(['plymouth hospitals nhs trust',
        'university hospitals plymouth nhs trust'], dtype=object),
 'RKB': array(['university hospitals coventry and warwickshire nhs trust'],
       dtype=object),
 'RKE': array(['the whittington hospital nhs trust',
        'whittington health nhs trust'], dtype=object),
 'RL1': array(['the robert jones and agnes hunt orthopaedic hospital nhs foundation trust'],
       dtype=object),
 'RL4': array(['the royal wolverhampton hospitals nhs trust',
        'the royal wolverhampton nhs trust'], dtype=object),
 'RLN': array(['city hospitals sunderland nhs foundation trust'], dtype=object),
 'RLQ': array(['hereford hospitals nhs trust', 'wye valley nhs trust'],
       dtype=object),
 'RLT': array(['george eliot hospital nhs trust'], dtype=object),
 'RLU': array(["birmingham women's health care nhs foundation trust",
        "birmingham women's nhs foundation trust"], dtype=object),
 'RM1': array(['norfolk and norwich university hospital nhs foundation trust',
        'norfolk and norwich university hospitals nhs foundation trust'],
       dtype=object),
 'RM2': array(['university hospital of south manchester nhs foundation trust'],
       dtype=object),
 'RM3': array(['salford royal nhs foundation trust'], dtype=object),
 'RM4': array(['trafford healthcare nhs trust'], dtype=object),
 'RMC': array(['royal bolton hospital nhs foundation trust',
        'bolton nhs foundation trust'], dtype=object),
 'RMP': array(['tameside hospital nhs foundation trust',
        'tameside and glossop integrated care nhs foundation trust'],
       dtype=object),
 'RN1': array(['winchester and eastleigh healthcare nhs trust'], dtype=object),
 'RN3': array(['great western hospitals nhs foundation trust'], dtype=object),
 'RN5': array(['basingstoke and north hampshire nhs foundation trust',
        'hampshire hospitals nhs foundation trust'], dtype=object),
 'RN7': array(['dartford and gravesham nhs trust'], dtype=object),
 'RNA': array(['the dudley group of hospitals nhs foundation trust',
        'the dudley group nhs foundation trust'], dtype=object),
 'RNH': array(['newham university hospital nhs trust'], dtype=object),
 'RNJ': array(['barts and the london nhs trust'], dtype=object),
 'RNL': array(['north cumbria acute hospitals nhs trust',
        'north cumbria university hospitals nhs trust'], dtype=object),
 'RNQ': array(['kettering general hospital nhs foundation trust'], dtype=object),
 'RNS': array(['northampton general hospital nhs trust'], dtype=object),
 'RNZ': array(['salisbury nhs foundation trust'], dtype=object),
 'RP4': array(['great ormond street hospital for children nhs trust',
        'great ormond street hospital for children nhs foundation trust'],
       dtype=object),
 'RP5': array(['doncaster and bassetlaw hospitals nhs foundation trust',
        'doncaster and bassetlaw teaching hospitals nhs foundation trust'],
       dtype=object),
 'RP6': array(['moorfields eye hospital nhs foundation trust'], dtype=object),
 'RPA': array(['medway nhs foundation trust'], dtype=object),
 'RPC': array(['queen victoria hospital nhs foundation trust'], dtype=object),
 'RPL': array(['worthing and southlands hospitals nhs trust'], dtype=object),
 'RPY': array(['the royal marsden nhs foundation trust'], dtype=object),
 'RQ3': array(["birmingham children's hospital nhs foundation trust",
        "birmingham women's and children's nhs foundation trust"],
       dtype=object),
 'RQ6': array(['royal liverpool and broadgreen university hospitals nhs trust'],
       dtype=object),
 'RQ8': array(['mid essex hospital services nhs trust'], dtype=object),
 'RQM': array(['chelsea and westminster hospital nhs foundation trust'],
       dtype=object),
 'RQQ': array(['hinchingbrooke health care nhs trust'], dtype=object),
 'RQW': array(['the princess alexandra hospital nhs trust'], dtype=object),
 'RQX': array(['homerton university hospital nhs foundation trust'], dtype=object),
 'RR1': array(['heart of england nhs foundation trust'], dtype=object),
 'RR7': array(['gateshead health nhs foundation trust'], dtype=object),
 'RR8': array(['leeds teaching hospitals nhs trust'], dtype=object),
 'RRE': array(['south staffordshire and shropshire healthcare nhs foundation trust',
        'midlands partnership nhs foundation trust'], dtype=object),
 'RRF': array(['wrightington, wigan and leigh nhs foundation trust'], dtype=object),
 'RRJ': array(['the royal orthopaedic hospital nhs foundation trust'],
       dtype=object),
 'RRK': array(['university hospital birmingham nhs foundation trust',
        'university hospitals birmingham nhs foundation trust'],
       dtype=object),
 'RRV': array(['university college london hospitals nhs foundation trust'],
       dtype=object),
 'RT3': array(['royal brompton and harefield nhs trust',
        'royal brompton and harefield nhs foundation trust',
        'royal brompton & harefield nhs foundation trust'], dtype=object),
 'RTD': array(['the newcastle upon tyne hospitals nhs foundation trust'],
       dtype=object),
 'RTE': array(['gloucestershire hospitals nhs foundation trust'], dtype=object),
 'RTF': array(['northumbria healthcare nhs foundation trust'], dtype=object),
 'RTG': array(['derby hospitals nhs foundation trust',
        'derby teaching hospitals nhs foundation trust',
        'university hospitals of derby and burton nhs foundation trust'],
       dtype=object),
 'RTH': array(['oxford radcliffe hospitals nhs trust',
        'oxford university hospitals nhs trust',
        'oxford university hospitals nhs foundation trust'], dtype=object),
 'RTK': array(["ashford and st peter's hospitals nhs trust",
        "ashford and st peter's hospitals nhs foundation trust"],
       dtype=object),
 'RTP': array(['surrey and sussex healthcare nhs trust'], dtype=object),
 'RTR': array(['south tees hospitals nhs foundation trust'], dtype=object),
 'RTX': array(['university hospitals of morecambe bay nhs trust',
        'university hospitals of morecambe bay nhs foundation trust'],
       dtype=object),
 'RV8': array(['north west london hospitals nhs trust'], dtype=object),
 'RVJ': array(['north bristol nhs trust'], dtype=object),
 'RVL': array(['barnet and chase farm hospitals nhs trust'], dtype=object),
 'RVR': array(['epsom and st helier university hospitals nhs trust'], dtype=object),
 'RVV': array(['east kent hospitals university nhs foundation trust'],
       dtype=object),
 'RVW': array(['north tees and hartlepool nhs foundation trust'], dtype=object),
 'RVY': array(['southport and ormskirk hospital nhs trust'], dtype=object),
 'RW1': array(['southern health nhs foundation trust'], dtype=object),
 'RW3': array(['central manchester university hospitals nhs foundation trust'],
       dtype=object),
 'RW6': array(['pennine acute hospitals nhs trust'], dtype=object),
 'RWA': array(['hull and east yorkshire hospitals nhs trust',
        'hull university teaching hospitals nhs trust'], dtype=object),
 'RWD': array(['united lincolnshire hospitals nhs trust'], dtype=object),
 'RWE': array(['university hospitals of leicester nhs trust'], dtype=object),
 'RWF': array(['maidstone and tunbridge wells nhs trust'], dtype=object),
 'RWG': array(['west hertfordshire hospitals nhs trust'], dtype=object),
 'RWH': array(['east and north hertfordshire nhs trust'], dtype=object),
 'RWJ': array(['stockport nhs foundation trust'], dtype=object),
 'RWP': array(['worcestershire acute hospitals nhs trust'], dtype=object),
 'RWW': array(['warrington and halton hospitals nhs foundation trust'],
       dtype=object),
 'RWY': array(['calderdale and huddersfield nhs foundation trust'], dtype=object),
 'RX1': array(['nottingham university hospitals nhs trust'], dtype=object),
 'RXC': array(['east sussex hospitals nhs trust',
        'east sussex healthcare nhs trust'], dtype=object),
 'RXF': array(['mid yorkshire hospitals nhs trust'], dtype=object),
 'RXG': array(['south west yorkshire partnership nhs foundation trust'],
       dtype=object),
 'RXH': array(['brighton and sussex university hospitals nhs trust'], dtype=object),
 'RXK': array(['sandwell and west birmingham hospitals nhs trust'], dtype=object),
 'RXL': array(['blackpool, fylde and wyre hospitals nhs foundation trust',
        'blackpool teaching hospitals nhs foundation trust'], dtype=object),
 'RXN': array(['lancashire teaching hospitals nhs foundation trust'], dtype=object),
 'RXP': array(['county durham and darlington nhs foundation trust'], dtype=object),
 'RXQ': array(['buckinghamshire hospitals nhs trust',
        'buckinghamshire healthcare nhs trust'], dtype=object),
 'RXR': array(['east lancashire hospitals nhs trust'], dtype=object),
 'RXW': array(['shrewsbury and telford hospital nhs trust'], dtype=object),
 'RY5': array(['lincolnshire community health services nhs trust'], dtype=object),
 'RYJ': array(['imperial college healthcare nhs trust'], dtype=object),
 'RYQ': array(['south london healthcare nhs trust'], dtype=object),
 'RYR': array(['western sussex hospitals nhs trust',
        'western sussex hospitals nhs foundation trust'], dtype=object),
 'RYV': array(['cambridgeshire community services nhs trust'], dtype=object),
 'RYW': array(['birmingham community healthcare nhs trust',
        'birmingham community healthcare nhs foundation trust'],
       dtype=object),
 'RYX': array(['central london community healthcare nhs trust'], dtype=object)}

dict_local = {'5CN': 'Herefordshire, County of',
 '5D7': 'Newcastle upon Tyne',
 '5D8': 'North Tyneside',
 '5JE': 'Barnsley',
 '5M1': 'Birmingham',
 '5N6': 'Derbyshire',
 '5P6': 'West Sussex',
 '5PJ': 'Stoke-on-Trent',
 '5PK': 'Staffordshire',
 '5PL': 'Worcestershire',
 '5QC': 'Hampshire',
 '5QH': 'Gloucestershire',
 '5QL': 'Somerset',
 '5QM': 'Bournemouth, Christchurch and Poole',
 '5QT': 'Isle of Wight',
 'R0A': 'Manchester',
 'R1A': 'Worcestershire',
 'R1E': 'Stoke-on-Trent',
 'R1F': 'Isle of Wight',
 'R1H': 'Tower Hamlets',
 'R1J': 'Gloucestershire',
 'R1K': 'Brent',
 'RA2': 'Surrey',
 'RA3': 'North Somerset',
 'RA4': 'Somerset',
 'RA7': 'Bristol, City of',
 'RA9': 'Torbay',
 'RAE': 'Bradford',
 'RAJ': 'Southend-on-Sea',
 'RAL': 'Camden',
 'RAN': 'Harrow',
 'RAP': 'Enfield',
 'RAS': 'Hillingdon',
 'RAX': 'Kingston upon Thames',
 'RBA': 'Somerset',
 'RBB': 'Bath and North East Somerset',
 'RBD': 'Dorset',
 'RBF': 'Oxfordshire',
 'RBK': 'Walsall',
 'RBL': 'Wirral',
 'RBN': 'St. Helens',
 'RBQ': 'Liverpool',
 'RBS': 'Liverpool',
 'RBT': 'Cheshire East',
 'RBV': 'Manchester',
 'RBZ': 'Devon',
 'RC1': 'Bedford',
 'RC3': 'Ealing',
 'RC9': 'Luton',
 'RCB': 'York',
 'RCC': 'North Yorkshire',
 'RCD': 'North Yorkshire',
 'RCF': 'Bradford',
 'RCU': 'Sheffield',
 'RCX': 'Norfolk',
 'RD1': 'Bath and North East Somerset',
 'RD3': 'Bournemouth, Christchurch and Poole',
 'RD7': 'Slough',
 'RD8': 'Milton Keynes',
 'RDD': 'Thurrock',
 'RDR': 'Brighton and Hove',
 'RDU': 'Surrey',
 'RDY': 'Bournemouth, Christchurch and Poole',
 'RDZ': 'Bournemouth, Christchurch and Poole',
 'RE9': 'South Tyneside',
 'REF': 'Cornwall',
 'REM': 'Liverpool',
 'REP': 'Liverpool',
 'RET': 'Liverpool',
 'RF4': 'Havering',
 'RFF': 'Barnsley',
 'RFR': 'Rotherham',
 'RFS': 'Derbyshire',
 'RFW': 'Hounslow',
 'RG3': 'Bromley',
 'RGC': 'Waltham Forest',
 'RGM': 'Cambridgeshire',
 'RGN': 'Cambridgeshire',
 'RGP': 'Norfolk',
 'RGQ': 'Suffolk',
 'RGR': 'Suffolk',
 'RGT': 'Cambridgeshire',
 'RGZ': 'Bexley',
 'RH5': 'Somerset',
 'RH8': 'Devon',
 'RHM': 'Southampton',
 'RHQ': 'Sheffield',
 'RHU': 'Portsmouth',
 'RHW': 'Reading',
 'RJ1': 'Lambeth',
 'RJ2': 'Lewisham',
 'RJ6': 'Croydon',
 'RJ7': 'Wandsworth',
 'RJ8': 'Cornwall',
 'RJC': 'Warwickshire',
 'RJD': 'Staffordshire',
 'RJE': 'Stoke-on-Trent',
 'RJF': 'Staffordshire',
 'RJL': 'North Lincolnshire',
 'RJN': 'Cheshire East',
 'RJR': 'Cheshire West and Chester',
 'RJZ': 'Lambeth',
 'RK5': 'Nottinghamshire',
 'RK9': 'Plymouth',
 'RKB': 'Coventry',
 'RKE': 'Islington',
 'RL1': 'Shropshire',
 'RL4': 'Wolverhampton',
 'RLN': 'Sunderland',
 'RLQ': 'Herefordshire, County of',
 'RLT': 'Warwickshire',
 'RLU': 'Birmingham',
 'RM1': 'Norfolk',
 'RM2': 'Manchester',
 'RM3': 'Salford',
 'RM4': 'Trafford',
 'RMC': 'Bolton',
 'RMP': 'Tameside',
 'RN1': 'Hampshire',
 'RN3': 'Swindon',
 'RN5': 'Hampshire',
 'RN7': 'Kent',
 'RNA': 'Dudley',
 'RNH': 'Newham',
 'RNJ': 'Tower Hamlets',
 'RNL': 'Cumbria',
 'RNQ': 'Northamptonshire',
 'RNS': 'Northamptonshire',
 'RNZ': 'Wiltshire',
 'RP4': 'Camden',
 'RP5': 'Doncaster',
 'RP6': 'Islington',
 'RPA': 'Medway',
 'RPC': 'West Sussex',
 'RPL': 'West Sussex',
 'RPY': 'Sutton',
 'RQ3': 'Birmingham',
 'RQ6': 'Liverpool',
 'RQM': 'Kensington and Chelsea',
 'RQQ': 'Cambridgeshire',
 'RQW': 'Hertfordshire',
 'RQX': 'Hackney',
 'RR1': 'Birmingham',
 'RR7': 'Gateshead',
 'RR8': 'Leeds',
 'RRE': 'Staffordshire',
 'RRF': 'Lancashire',
 'RRJ': 'Birmingham',
 'RRK': 'Birmingham',
 'RRV': 'Camden',
 'RT3': 'Kensington and Chelsea',
 'RTD': 'Newcastle upon Tyne',
 'RTE': 'Gloucestershire',
 'RTF': 'North Tyneside',
 'RTG': 'Derby',
 'RTH': 'Oxfordshire',
 'RTK': 'Surrey',
 'RTP': 'West Sussex',
 'RTR': 'Middlesbrough',
 'RTX': 'Cumbria',
 'RV8': 'Camden',
 'RVJ': 'Bristol, City of',
 'RVL': 'Barnet',
 'RVR': 'Surrey',
 'RVV': 'Kent',
 'RVW': 'Stockton-on-Tees',
 'RVY': 'Sefton',
 'RW1': 'Hampshire',
 'RW3': 'Manchester',
 'RW6': 'Oldham',
 'RWA': 'Kingston upon Hull, City of',
 'RWD': 'Lincolnshire',
 'RWE': 'Leicester',
 'RWF': 'Kent',
 'RWG': 'Hertfordshire',
 'RWH': 'Hertfordshire',
 'RWJ': 'Stockport',
 'RWP': 'Worcestershire',
 'RWW': 'Warrington',
 'RWY': 'Kirklees',
 'RX1': 'Nottingham',
 'RXC': 'East Sussex',
 'RXF': 'Wakefield',
 'RXG': 'Wakefield',
 'RXH': 'Brighton and Hove',
 'RXK': 'Sandwell',
 'RXL': 'Blackpool',
 'RXN': 'Lancashire',
 'RXP': 'Darlington',
 'RXQ': 'Buckinghamshire',
 'RXR': 'Lancashire',
 'RXW': 'Shropshire',
 'RY5': 'Lincolnshire',
 'RYJ': 'Westminster',
 'RYQ': 'Southwark',
 'RYR': 'West Sussex',
 'RYV': 'Cambridgeshire',
 'RYW': 'Birmingham',
 'RYX': 'Westminster',
 'RDE': 'Essex',
 'RQ8': 'Essex'}